controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:
      type: forward_command_controller/ForwardCommandController

joint_group_position_controller:
  ros__parameters:
    interface_name: position
    joints:
      - rf_hip_joint
      - rf_upper_leg_joint
      - rf_lower_leg_joint
      - lf_hip_joint
      - lf_upper_leg_joint
      - lf_lower_leg_joint
      - rh_hip_joint
      - rh_upper_leg_joint
      - rh_lower_leg_joint
      - lh_hip_joint
      - lh_upper_leg_joint
      - lh_lower_leg_joint

